spring.application.name=spring-boot-webflux-apirest
spring.data.mongodb.uri=mongodb://localhost:27017/spring_boot_webflux

config.uploads.path=C:\\SpringWebFlux\\uploads\\

#ruta que queremos testear
config.base.endpoint=/api/productos

#ruta de ProductoHandler para testear apis con WebTestClient
config.base.endpointHandler=/api/v2/productos

#ruta de ProductoController para testear apis con WebTestClient
config.base.endpointRestController=/api/productos